- name: ensure mythtv backup directory exists
  file:
    dest: "{{ mythtv_backup_directory }}"
    state: directory
    owner: mythtv
    group: mythtv
    mode: 0750

- name: ensure mythtv backup configuration is installed
  template:
    src: backuprc.j2
    dest: /etc/mythtv/backuprc
    owner: mythtv
    group: mythtv
    mode: 0640

- name: ensure systemd service for backup is installed
  copy:
    src: backup.service
    dest: /etc/systemd/system/mythtv-backup.service

- name: ensure systemd timer for backup is installed
  copy:
    src: backup.timer
    dest: /etc/systemd/system/mythtv-backup.timer

- name: ensure systemd timer for backup is enabled
  service:
    name: mythtv-backup.timer
    state: started
    enabled: yes
