- name: ensure mythtv backup directory exists
  file:
    dest: "{{ mythtv_backup_directory }}"
    state: directory
    owner: mythtv
    group: mythtv
    mode: 0750

- name: ensure mythtv backup configuration is installed
  template:
    src: backuprc.j2
    dest: /etc/mythtv/backuprc
    owner: mythtv
    group: mythtv
    mode: 0640

- name: ensure mythtv database backup cron script is installed
  cron:
    name: mythtv backup
    cron_file: mythtv_backup
    user: mythtv
    hour: 6
    job: /usr/share/mythtv/mythconverg_backup.pl
